### ISSUE TITLE
General question

### ISSUE THREAD

**Issue by systats** [larsvancutsem/piratings#1]
Hi - nice package, exactly what I need right now ;) One question remains open for me: do I have to shift the pi/ elo ratings in date before joining back to my games dataframe?

Thanks in advance!
Best,
Sy

**Comment by systats** [comment]
And maybe a second one: do you think it makes sense to use not only goal difference as outcome for pi ratings but also other team stats like shots on goal, ball possession time or cards?

**Comment by larsvancutsem** [comment]
Hey systats,

First of all, thanks for liking the package ;)

Now, with regard to your questions, the pi ratings that are returned by the package are the ones that each team has before the match in question (no need to shift back for prediction purposes etc. :) ). 

Regarding the second question (I'm assuming you mean historical team stats), the factors you mention do appear in research concerning the home advantage, which the pi rating system captures to a great extent. ("Home advantage in soccer – A matter of expectations, goal setting and tactical decisions of coaches?" by Staufenbiel e.a.; "HOME ADVANTAGE IN TURKISH PROFESSIONAL SOCCER" by Seckin; "Home advantage and player nationality in international club football." by Poulter).

But, in my opinion, it can definitely be an interesting addition to the model!

Best,
Lars
