### ISSUE TITLE
Optimization of lambda and gamma

### ISSUE THREAD

**Issue by systats** [larsvancutsem/piratings#2]
Hi again! I am trying to optimize the PI model by league/season and get very different performances per league. Do you see room for improvement?

![image](https://user-images.githubusercontent.com/22753281/58012616-25b97c80-7af5-11e9-9432-8dacbaef3d55.png)

Here you see again the huge variation between the leagues

![image](https://user-images.githubusercontent.com/22753281/58013688-6e723500-7af7-11e9-8062-af582bb6d400.png)

btw thanks for responding so fast!
Sy

**Comment by larsvancutsem** [comment]
Hey Systats,

One thing I can definitely point out is that in an international setting such as Playoffs, Champions League and Europa League, etc.., teams from different national leagues play against each other. There should be room for improvement when building the pi-ratings for the teams first in the national leagues and taking those rates along to the international games. As far I know, the pi-ratings haven't been tested extensively yet in an international setting. 

I do think that Elo-rating are definitely worth looking into as well and might bring improvement!

Good luck!
Lars
