### ISSUE TITLE
Learning rate for lambda and gamma

### ISSUE THREAD

**Issue by NazimR** [larsvancutsem/piratings#3]
Hi,

Firstly, I would like to thank you for this awesome package and I really appreciate it :). Im try to recreate the pi-rating from work of Constantinou and Fenton (2012). They use 20 EPL season (1992/1993 to 2011/2012). The first 5 EPL season (1992/1993 to 1996/1997) are for generating the initial ratings for the competing teams, 10 season (1997/1998 to 2006/2007) to learn the parameters lambda and gamma and the last 5 EPL season (2007/2008 to 2011/2012) for prediction. 

The question is  when I run the optimization of lambda and gamma, why the result that I obtained is not exactly the same as the value of minimum squared error of expected goal difference observed in Constantinou and Fenton (2012) using the 10 EPL season (1997/1998 to 2006/2007) which I extracted from same source (Football-Data.co.uk)?. 

**Constantinou and Fenton (2012) result:**
lambda = 0.035.
gamma = 0.7.
error squared = 2.6247. 

**My result:**
lambda = 0.045.
gamma = 0.45.
error squared = 2.555431.

I really appreciate your help and thanks in advance, Regards.
NazimR

**Comment by larsvancutsem** [comment]
Hi NazimR,

First of all, thank you for liking the package and, thanks for bringing this discrepancy to my attention. Although I haven't been able to validate the code extensively on the data used by Constantinou, the code should accurately reflect the approach taken in the paper. A comparison of squared goal differences might yield a clue to where the discrepancy might be. I did however test predictive power of the pi-ratings created using this package & they were statistically significant (p<0.0001) and yielded better results than elo-ratings in various cases. 

However, I will test it using Constantinou's data and, update the package as soon as I find a discrepancy between any of the plots.

Kind regards,
Lars

**Comment by NazimR** [comment]
Hi Lars,

Thank you for your response. Here, I attach the data that I extracted for your reference and thank you again for this awesome package :).
[RAW - EDITED.zip](https://github.com/larsvancutsem/piratings/files/3532749/RAW.-.EDITED.zip)

Kind regards,
NazimR
